# Generated by Django 4.2 on 2024-11-26 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=255)),
                ('deck_name', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=64)),
                ('front_text', models.TextField()),
                ('back_text', models.TextField()),
                ('embedding_vector', models.BinaryField()),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('content', models.TextField()),
                ('embedding_vector', models.BinaryField()),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='cardembedding',
            index=models.Index(fields=['content_hash'], name='api_cardemb_content_a7c0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='cardembedding',
            index=models.Index(fields=['deck_name'], name='api_cardemb_deck_na_4ba2c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardembedding',
            unique_together={('card_id', 'deck_name', 'model_name')},
        ),
    ]
