# Generated by Django 4.2 on 2024-11-30 09:57

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_cardembedding_delete_pdfembedding_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processingtask",
            options={
                "verbose_name": "Processing Task",
                "verbose_name_plural": "Processing Tasks",
            },
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="progress_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="processingtask",
            index=models.Index(
                fields=["task_id"], name="api_process_task_id_d332d8_idx"
            ),
        ),
    ]
